# Generated by Django 4.2.4 on 2023-08-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('date_of_joining', models.PositiveIntegerField()),
                ('this_year_credit', models.PositiveIntegerField()),
                ('total_credit', models.PositiveIntegerField()),
                ('total_titles', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
