# Generated by Django 4.2.4 on 2023-08-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_age_player_no_of_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_joining',
            field=models.DateField(),
        ),
    ]
