# Generated by Django 4.2.4 on 2023-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_joining',
            field=models.PositiveIntegerField(),
        ),
    ]
