# Generated by Django 4.2.4 on 2023-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_player_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_awards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('teams', models.ManyToManyField(related_name='state', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='league',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teams', models.ManyToManyField(related_name='leagues', to='api.player')),
            ],
        ),
    ]
