# Generated by Django 4.1.3 on 2023-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_player_total_awards_state_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_joining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='this_year_credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_credit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_titles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
